Convars.SetValue("cl_ejectbrass", "0")
Convars.SetValue("cl_impacteffects_limit_exit", "3")
Convars.SetValue("cl_impacteffects_limit_general", "3")
Convars.SetValue("cl_impacteffects_limit_water", "3")
Convars.SetValue("cl_new_impact_effects", "0")
Convars.SetValue("cl_pred_optimize", "1")
Convars.SetValue("con_filter_text_out", "particle")
Convars.SetValue("dsp_slow_cpu", "1") // Disable initialization of enhanced spatialization
Convars.SetValue("fast_fogvolume", "1")
Convars.SetValue("flex_rules", "0") // Disable facial animations
Convars.SetValue("func_break_max_pieces", "3")//rep
Convars.SetValue("mat_force_vertexfog", "0")
Convars.SetValue("mat_forcehardwaresync", "0") // Keep the CPU submission within 1 to 2 frames of the GPU
Convars.SetValue("mat_framebuffercopyoverlaysize", "0")
Convars.SetValue("mat_max_worldmesh_vertices", "2")
Convars.SetValue("mat_reducefillrate", "1")
Convars.SetValue("mat_software_aa_blur_one_pixel_lines", "0")
Convars.SetValue("mat_software_aa_edge_threshold", "9")
Convars.SetValue("mat_software_aa_quality", "0")
Convars.SetValue("mat_software_aa_strength", "0")
Convars.SetValue("mat_software_aa_strength_vgui", "0")
Convars.SetValue("mat_software_aa_tap_offset", "0")
Convars.SetValue("mod_load_anims_async", "1")
Convars.SetValue("mod_load_mesh_async", "1")
Convars.SetValue("mod_load_vcollide_async", "1")
Convars.SetValue("net_compresspackets", "0")
Convars.SetValue("phonemedelay", "-30")
Convars.SetValue("phonemefilter", "0.01")
Convars.SetValue("phonemesnap", "0")
Convars.SetValue("r_3dsky", "0")
Convars.SetValue("r_DrawDetailProps", "0")
Convars.SetValue("r_WaterDrawReflection", "0")
Convars.SetValue("r_WaterDrawRefraction", "0")
Convars.SetValue("r_ambientboost", "0") // Disable to save the small amount of CPU this uses
Convars.SetValue("r_ambientfactor", "0")
Convars.SetValue("r_ambientfraction", "0")
Convars.SetValue("r_ambientmin", "0")
Convars.SetValue("r_decals", "0")
Convars.SetValue("r_draw_flashlight_3rd_person", "0")
Convars.SetValue("r_drawmodelstatsoverlaydistance", "0")
Convars.SetValue("r_drawmodelstatsoverlaymax", "0")
Convars.SetValue("r_drawmodelstatsoverlaymin", "0")
Convars.SetValue("r_dynamic", "0")
Convars.SetValue("r_fastzreject", "1") // Early Z pass. Uses the CPU to prevent overdraw.
Convars.SetValue("r_flashlightmuzzleflash", "0")
Convars.SetValue("r_flex", "0") // Disable facial animations
Convars.SetValue("r_glint_procedural", "1")
Convars.SetValue("r_jiggle_bones", "0")
Convars.SetValue("r_lightaverage", "0") // Disable this lighting job that uses a lot of CPU even if it is not needed/noticeable
Convars.SetValue("r_maxdlights", "0")
Convars.SetValue("r_maxnewsamples", "0")
Convars.SetValue("r_maxsampledist", "32")
Convars.SetValue("r_pixelfog", "0")
Convars.SetValue("r_pixelvisibility_partial", "0")
Convars.SetValue("r_renderoverlayfragment", "0")
//Convars.SetValue("r_rootlod", "1")
//Convars.SetValue("r_staticprop_lod", "4")
Convars.SetValue("r_lod", "2")
Convars.SetValue("r_ropetranslucent", "0")
Convars.SetValue("r_propsmaxdist", "600")
Convars.SetValue("cl_detaildist", "0")
Convars.SetValue("cl_detailfade", "0")
Convars.SetValue("rope_averagelight", "0")
Convars.SetValue("rope_collide", "0") // Skip CPU heavy world collisions for ropes
Convars.SetValue("rope_rendersolid", "0") // Skip rendering solid part of ropes
Convars.SetValue("rope_shake", "0")
Convars.SetValue("rope_smooth", "0") // Skip a long smoothing operation for ropes
Convars.SetValue("rope_subdiv", "0") // Skip heavy loops for rope subdivisions
Convars.SetValue("rope_wind_dist", "0") // Do not apply CPU intensive wind to ropes
//Convars.SetValue("r_worldlights", "1")
Convars.SetValue("snd_delay_sound_shift", "0.03")
Convars.SetValue("snd_mix_async", "0")
Convars.SetValue("snd_mixahead", "0.1")
Convars.SetValue("snd_pitchquality", "0")